// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

	public class GameConfig
	{
			public static bool ENABLE_ANALYTICS = true;		// See Assets/Readme.txt for instructions on how to use analytics
			public static int ANALYTICS_RULE_ID = 0; //147;		// See Assets/Readme.txt for instructions on how to replace this ID and use analytics
	}


